name: Simulation

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo     
  push:
    branches:
      - master
    paths:
      - src/Simulation/**      

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}               

      - name: Get Secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_NAME }}
          secrets: 'registryServer,registryUsername,registryPassword'
        id: getSecrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.getSecrets.outputs.registryServer }}
          username: ${{ steps.getSecrets.outputs.registryUsername }}
          password: ${{ steps.getSecrets.outputs.registryPassword }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./master/src/Simulation
          push: true
          tags: ${{ steps.getSecrets.outputs.registryServer }}/simulation:${{ github.sha }}
          file:  ./master/src/Simulation/dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    

      - name: Get Secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_NAME }}
          secrets: 'resourceGroup,registryServer,registryUsername,registryPassword,appInsightsInstrumentationKey,eventHubNsConnectionString,containerInstanceSubnetId'
        id: getSecrets         

      - name: Generate variables
        run: |           
           if ["${{ steps.getSecrets.outputs.containerInstanceSubnetId }}" != ""]
           then
             echo "SUBNET=--subnet ${{ steps.getSecrets.outputs.containerInstanceSubnetId }}" >> $GITHUB_ENV 
           fi

      - name: Deploy to ACI
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Starting Deploying"
            az container create -n simulation -g ${{ steps.getSecrets.outputs.resourceGroup }} --registry-login-server ${{ steps.getSecrets.outputs.registryServer }} --registry-username ${{ steps.getSecrets.outputs.registryUsername }} --registry-password ${{ steps.getSecrets.outputs.registryPassword }} --image ${{ steps.getSecrets.outputs.registryServer }}/simulation:${{ github.sha }} ${{ env.SUBNET }} --secure-environment-variables "APPINSIGHTS_INSTRUMENTATIONKEY=${{ steps.getSecrets.outputs.appInsightsInstrumentationKey }}" "EH_CONNECTIONSTRING=${{ steps.getSecrets.outputs.eventHubNsConnectionString }}" --debug