name: VehicleRegistrationService

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo     
  push:
    branches:
      - master
    paths:
      - src/VehicleRegistrationService/**      

  # Allow mannually trigger 
  workflow_dispatch:
    inputs:
      action:
        description: 'Action (create or update)'
        required: true
        default: 'update'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}               

      - name: Get Secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_NAME }}
          secrets: 'registryServer,registryUsername,registryPassword'
        id: getSecrets

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ steps.getSecrets.outputs.registryServer }}
          username: ${{ steps.getSecrets.outputs.registryUsername }}
          password: ${{ steps.getSecrets.outputs.registryPassword }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./master/src/VehicleRegistrationService
          push: true
          tags: ${{ steps.getSecrets.outputs.registryServer }}/vehicleregistrationservice:${{ github.sha }}
          file:  ./master/src/VehicleRegistrationService/Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        with:
          path: master

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}        

      - name: Get Secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_NAME }}
          secrets: 'resourceGroup,registryServer,registryUsername,registryPassword,environmentId'
        id: getSecrets          

      - name: Generate variables
        run: |           
           if [ "${{ github.event.inputs.action }}" == "" ]
           then
             echo "ACTION=update" >> $GITHUB_ENV 
           else
             echo "ACTION=${{ github.event.inputs.action }}" >> $GITHUB_ENV 
           fi
           echo REVISION_SUFFIX=`echo "${{ github.sha }}" | cut -c 1-7` >> $GITHUB_ENV
        
      - name: Replace tokens in yaml file
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./master/src/containerapps/vehicleregistrationservice.yaml"]'
        env: 
          registry-server: ${{ steps.getSecrets.outputs.registryServer }}
          registry-username: ${{ steps.getSecrets.outputs.registryUsername }}
          registry-password: ${{ steps.getSecrets.outputs.registryPassword }}
          environment-id:  ${{ steps.getSecrets.outputs.environmentId }}
          image-tag: ${{ github.sha }}          
          revision-suffix: ${{ env.REVISION_SUFFIX }}
    
      - name: Output file
        run: cat ./master/src/containerapps/vehicleregistrationservice.yaml          

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            echo "Installing containerapp extension"
            #az provider register --namespace Microsoft.App
            az extension add --name containerapp --yes
            echo "Starting Deploying"
            az containerapp ${{ env.ACTION }} -n vehicleregistrationservice -g ${{ steps.getSecrets.outputs.resourceGroup }} --yaml ./master/src/containerapps/vehicleregistrationservice.yaml --debug
